CREATE OR REPLACE PROCEDURE place_order (
    p_user_id          IN NUMBER,
    p_pickup_window_id IN NUMBER,
    p_menu_item_ids    IN SYS.ODCINUMBERLIST,
    p_quantities       IN SYS.ODCINUMBERLIST,
    p_order_id         OUT NUMBER,
    p_pickup_code      OUT VARCHAR2,
    p_total_amount     OUT NUMBER
)
AS
    v_window_capacity NUMBER;
    v_reserved_count  NUMBER;
    v_item_price      NUMBER;
    v_available_qty   NUMBER;
    v_order_id        NUMBER;
    v_temp_code       VARCHAR2(100);
    v_pickup_code     VARCHAR2(100);
    v_total_amount    NUMBER := 0;
BEGIN
    /*
        Basic validation.
    */

    IF p_menu_item_ids IS NULL
       OR p_quantities IS NULL
       OR p_menu_item_ids.COUNT = 0
    THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Order must contain at least one item.'
        );
    END IF;

    IF p_menu_item_ids.COUNT <> p_quantities.COUNT THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Item and quantity counts must match.'
        );
    END IF;


    /*
        Lock pickup window.

        This prevents two concurrent orders from
        exceeding the pickup-window capacity.
    */

    SELECT
        capacity,
        reserved_count
    INTO
        v_window_capacity,
        v_reserved_count
    FROM pickup_windows
    WHERE pickup_window_id = p_pickup_window_id
    FOR UPDATE;


    /*
        Only one reservation is created per order.
    */

    IF v_reserved_count + 1 > v_window_capacity THEN
        RAISE_APPLICATION_ERROR(
            -20006,
            'Pickup window is full.'
        );
    END IF;


    /*
        Validate every requested item and lock its stock row.

        Locking the stock row prevents concurrent orders
        from overselling the same item.
    */

    FOR i IN 1 .. p_menu_item_ids.COUNT
    LOOP

        IF p_quantities(i) <= 0 THEN
            RAISE_APPLICATION_ERROR(
                -20003,
                'Order quantity must be greater than zero.'
            );
        END IF;


        /*
            Lock menu item and obtain current price.
        */

        BEGIN

            SELECT price
            INTO v_item_price
            FROM menu_items
            WHERE menu_item_id = p_menu_item_ids(i)
              AND is_available = 'Y'
            FOR UPDATE;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN

                RAISE_APPLICATION_ERROR(
                    -20004,
                    'Menu item is unavailable or does not exist.'
                );

        END;


        /*
            Lock stock row.
        */

        BEGIN

            SELECT available_qty
            INTO v_available_qty
            FROM stock
            WHERE menu_item_id = p_menu_item_ids(i)
            FOR UPDATE;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN

                RAISE_APPLICATION_ERROR(
                    -20005,
                    'Stock record does not exist for menu item.'
                );

        END;


        /*
            Prevent overselling.
        */

        IF v_available_qty < p_quantities(i) THEN
            RAISE_APPLICATION_ERROR(
                -20005,
                'Insufficient stock for menu item '
                || p_menu_item_ids(i)
                || '. Available: '
                || v_available_qty
            );
        END IF;


        /*
            Calculate order total.
        */

        v_total_amount :=
            v_total_amount
            + (v_item_price * p_quantities(i));

    END LOOP;


    /*
        Temporary collision-safe pickup code.

        The temporary value is used because ORDER_ID is
        generated by Oracle during the INSERT.
    */

    v_temp_code :=
        'CAF' ||
        SUBSTR(
            RAWTOHEX(SYS_GUID()),
            1,
            17
        );


    /*
        Create order.

        Oracle generates ORDER_ID through the identity column.
    */

    INSERT INTO orders (
        user_id,
        pickup_window_id,
        pickup_code,
        order_status,
        total_amount
    )
    VALUES (
        p_user_id,
        p_pickup_window_id,
        v_temp_code,
        'PLACED',
        v_total_amount
    )
    RETURNING order_id INTO v_order_id;


    /*
        Final deterministic pickup code.

        Format:
            CAF + 17 digit ORDER_ID

        Example:
            CAF00000000000000141
    */

    v_pickup_code :=
        'CAF' ||
        LPAD(
            TO_CHAR(v_order_id),
            17,
            '0'
        );


    UPDATE orders
    SET pickup_code = v_pickup_code
    WHERE order_id = v_order_id;


    /*
        Insert order lines and consume stock.
    */

    FOR i IN 1 .. p_menu_item_ids.COUNT
    LOOP

        SELECT price
        INTO v_item_price
        FROM menu_items
        WHERE menu_item_id = p_menu_item_ids(i);


        INSERT INTO order_lines (
            order_id,
            menu_item_id,
            quantity,
            unit_price
        )
        VALUES (
            v_order_id,
            p_menu_item_ids(i),
            p_quantities(i),
            v_item_price
        );


        UPDATE stock
        SET available_qty =
            available_qty - p_quantities(i)
        WHERE menu_item_id = p_menu_item_ids(i);

    END LOOP;


    /*
        Reserve one pickup-window slot.
    */

    UPDATE pickup_windows
    SET reserved_count = reserved_count + 1
    WHERE pickup_window_id = p_pickup_window_id;


    /*
        Return values to caller.
    */

    p_order_id     := v_order_id;
    p_pickup_code  := v_pickup_code;
    p_total_amount := v_total_amount;


    COMMIT;

EXCEPTION

    WHEN NO_DATA_FOUND THEN

        ROLLBACK;

        RAISE_APPLICATION_ERROR(
            -20007,
            'Pickup window or required order data was not found.'
        );

    WHEN OTHERS THEN

        ROLLBACK;
        RAISE;

END;
/

CREATE OR REPLACE PROCEDURE update_order_status (
    p_order_id    IN NUMBER,
    p_new_status  IN VARCHAR2,
    p_changed_by  IN NUMBER
)
AS
    v_current_status       VARCHAR2(20);
    v_pickup_window        NUMBER;
    v_previous_identifier  VARCHAR2(64);
BEGIN

    /*
        Preserve the current Oracle session identifier.

        This allows the trigger to know which authenticated
        staff/admin user performed the status transition.
    */

    v_previous_identifier :=
        SYS_CONTEXT(
            'USERENV',
            'CLIENT_IDENTIFIER'
        );


    /*
        Lock the order while changing its status.
    */

    SELECT
        order_status,
        pickup_window_id
    INTO
        v_current_status,
        v_pickup_window
    FROM orders
    WHERE order_id = p_order_id
    FOR UPDATE;


    /*
        Validate requested status.
    */

    IF p_new_status NOT IN (
        'PLACED',
        'PREPARING',
        'READY',
        'COLLECTED'
    )
    THEN

        RAISE_APPLICATION_ERROR(
            -20020,
            'Invalid order status.'
        );

    END IF;


    /*
        Prevent invalid backward or skipped transitions.
    */

    IF v_current_status = 'PLACED'
       AND p_new_status <> 'PREPARING'
    THEN

        RAISE_APPLICATION_ERROR(
            -20021,
            'PLACED orders can only move to PREPARING.'
        );


    ELSIF v_current_status = 'PREPARING'
       AND p_new_status <> 'READY'
    THEN

        RAISE_APPLICATION_ERROR(
            -20022,
            'PREPARING orders can only move to READY.'
        );


    ELSIF v_current_status = 'READY'
       AND p_new_status <> 'COLLECTED'
    THEN

        RAISE_APPLICATION_ERROR(
            -20023,
            'READY orders can only move to COLLECTED.'
        );


    ELSIF v_current_status IN (
        'COLLECTED',
        'CANCELLED'
    )
    THEN

        RAISE_APPLICATION_ERROR(
            -20024,
            'Completed or cancelled orders cannot change status.'
        );

    END IF;


    /*
        Set the authenticated actor for the trigger.

        CLIENT_IDENTIFIER is session-scoped and does not
        require a custom application context.
    */

    DBMS_SESSION.SET_IDENTIFIER(
        TO_CHAR(p_changed_by)
    );


    /*
        Update the order status.

        The status-history trigger fires here and reads
        CLIENT_IDENTIFIER as CHANGED_BY.
    */

    UPDATE orders
    SET order_status = p_new_status
    WHERE order_id = p_order_id;


    /*
        When the order is collected, release its
        pickup-window reservation.

        Stock is NOT restored because the food has
        already been fulfilled.
    */

    IF p_new_status = 'COLLECTED' THEN

        UPDATE pickup_windows
        SET reserved_count =
            CASE
                WHEN reserved_count > 0
                THEN reserved_count - 1
                ELSE 0
            END
        WHERE pickup_window_id = v_pickup_window;

    END IF;


    /*
        Restore the previous session identifier before
        committing the transaction.
    */

    DBMS_SESSION.SET_IDENTIFIER(
        v_previous_identifier
    );


    COMMIT;


EXCEPTION

    WHEN NO_DATA_FOUND THEN

        ROLLBACK;

        DBMS_SESSION.SET_IDENTIFIER(
            v_previous_identifier
        );

        RAISE_APPLICATION_ERROR(
            -20025,
            'Order not found.'
        );


    WHEN OTHERS THEN

        ROLLBACK;

        DBMS_SESSION.SET_IDENTIFIER(
            v_previous_identifier
        );

        RAISE;

END;
/