-- ============================================================
-- CAMPUS CAFETERIA PREORDER & PICKUP
-- PostgreSQL 18 Schema
-- ============================================================

BEGIN;

-- ============================================================
-- ROLES
-- ============================================================

CREATE TABLE roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    role_name   VARCHAR(20) NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_roles_name UNIQUE (role_name)
);

-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    role_id         INTEGER NOT NULL,
    full_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id),

    CONSTRAINT ck_users_active
        CHECK (is_active IN ('Y', 'N'))
);

-- ============================================================
-- MENU DATES
-- ============================================================

CREATE TABLE menu_dates (
    menu_date_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    menu_date       DATE NOT NULL,
    is_published    CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_menu_dates PRIMARY KEY (menu_date_id),
    CONSTRAINT uq_menu_dates_date UNIQUE (menu_date),

    CONSTRAINT ck_menu_dates_published
        CHECK (is_published IN ('Y', 'N'))
);

-- ============================================================
-- MENU ITEMS
-- ============================================================

CREATE TABLE menu_items (
    menu_item_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    menu_date_id        INTEGER NOT NULL,
    item_name           VARCHAR(100) NOT NULL,
    description         VARCHAR(500),
    price               NUMERIC(8,2) NOT NULL,
    is_available        CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_menu_items PRIMARY KEY (menu_item_id),

    CONSTRAINT fk_menu_items_date
        FOREIGN KEY (menu_date_id)
        REFERENCES menu_dates(menu_date_id),

    CONSTRAINT ck_menu_items_price
        CHECK (price > 0),

    CONSTRAINT ck_menu_items_available
        CHECK (is_available IN ('Y', 'N'))
);

-- ============================================================
-- INGREDIENTS
-- ============================================================

CREATE TABLE ingredients (
    ingredient_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ingredient_name     VARCHAR(100) NOT NULL,

    CONSTRAINT pk_ingredients PRIMARY KEY (ingredient_id),
    CONSTRAINT uq_ingredients_name UNIQUE (ingredient_name)
);

-- ============================================================
-- MENU ITEM <-> INGREDIENT
-- ============================================================

CREATE TABLE item_ingredients (
    menu_item_id    INTEGER NOT NULL,
    ingredient_id   INTEGER NOT NULL,

    CONSTRAINT pk_item_ingredients
        PRIMARY KEY (menu_item_id, ingredient_id),

    CONSTRAINT fk_ii_menu_item
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items(menu_item_id),

    CONSTRAINT fk_ii_ingredient
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients(ingredient_id)
);

-- ============================================================
-- STOCK
-- ============================================================

CREATE TABLE stock (
    menu_item_id    INTEGER NOT NULL,
    available_qty   INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT pk_stock PRIMARY KEY (menu_item_id),

    CONSTRAINT fk_stock_menu_item
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items(menu_item_id),

    CONSTRAINT ck_stock_qty
        CHECK (available_qty >= 0)
);

-- ============================================================
-- PICKUP WINDOWS
-- ============================================================

CREATE TABLE pickup_windows (
    pickup_window_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    window_date         DATE NOT NULL,
    start_time          TIMESTAMP NOT NULL,
    end_time            TIMESTAMP NOT NULL,
    capacity            INTEGER NOT NULL,
    reserved_count      INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT pk_pickup_windows PRIMARY KEY (pickup_window_id),

    CONSTRAINT ck_pickup_capacity
        CHECK (capacity > 0),

    CONSTRAINT ck_pickup_reserved
        CHECK (reserved_count >= 0),

    CONSTRAINT ck_pickup_time
        CHECK (end_time > start_time),

    CONSTRAINT ck_pickup_reserved_capacity
        CHECK (reserved_count <= capacity),

    CONSTRAINT uq_pickup_window
        UNIQUE (window_date, start_time)
);

-- ============================================================
-- ORDERS
-- ============================================================

CREATE TABLE orders (
    order_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id            INTEGER NOT NULL,
    pickup_window_id   INTEGER NOT NULL,
    pickup_code        VARCHAR(20) NOT NULL,
    order_status       VARCHAR(20) DEFAULT 'PLACED' NOT NULL,
    total_amount       NUMERIC(10,2) DEFAULT 0 NOT NULL,
    ordered_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cancelled_at       TIMESTAMP,

    CONSTRAINT pk_orders PRIMARY KEY (order_id),

    CONSTRAINT uq_orders_pickup_code
        UNIQUE (pickup_code),

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_orders_pickup
        FOREIGN KEY (pickup_window_id)
        REFERENCES pickup_windows(pickup_window_id),

    CONSTRAINT ck_orders_status
        CHECK (
            order_status IN (
                'PLACED',
                'PREPARING',
                'READY',
                'COLLECTED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_orders_total
        CHECK (total_amount >= 0)
);

-- ============================================================
-- ORDER LINES
-- ============================================================

CREATE TABLE order_lines (
    order_id       INTEGER NOT NULL,
    menu_item_id   INTEGER NOT NULL,
    quantity       INTEGER NOT NULL,
    unit_price     NUMERIC(8,2) NOT NULL,

    CONSTRAINT pk_order_lines
        PRIMARY KEY (order_id, menu_item_id),

    CONSTRAINT fk_order_lines_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_lines_item
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items(menu_item_id),

    CONSTRAINT ck_order_lines_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_order_lines_price
        CHECK (unit_price > 0)
);

-- ============================================================
-- ORDER STATUS HISTORY
-- ============================================================

CREATE TABLE order_status_history (
    history_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    order_id        INTEGER NOT NULL,
    old_status      VARCHAR(20),
    new_status      VARCHAR(20) NOT NULL,
    changed_by      INTEGER,
    changed_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_status_history PRIMARY KEY (history_id),

    CONSTRAINT fk_history_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_history_user
        FOREIGN KEY (changed_by)
        REFERENCES users(user_id)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_menu_items_date
    ON menu_items(menu_date_id);

CREATE INDEX idx_orders_user
    ON orders(user_id);

CREATE INDEX idx_orders_status
    ON orders(order_status);

CREATE INDEX idx_orders_pickup
    ON orders(pickup_window_id);

CREATE INDEX idx_history_order
    ON order_status_history(order_id);

CREATE INDEX idx_pickup_windows_date
    ON pickup_windows(window_date);

COMMIT;